### ISSUE TITLE
License and Python version requirements update

### ISSUE THREAD

**Issue by azakkerman** [ikollipara/monadic-error#4]
Hi, thanks for the library, but I encountered a few issues:
- I wanted to use it with Python 3.10 but on pypi the module requires >=3.12
- Could you publish it under some open source license to be able to use it at my work?
Thank you!

**Comment by ikollipara** [comment]
I've added a License so you should be good on that front. I thought I had originally.

The package is built using some of Python 3.12's new tooling, which makes it incompatible with older versions.
I have an older PYPI version that uses 3.10, which you could use.
